# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
  
    config.vm.define "web" do |web|
        web.vm.box="luki_strike/Ubuntu"
        web.vm.synced_folder ".", "/vagrant"
        web.vm.hostname = "web"
        web.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        web.vm.network "private_network", ip: "192.168.100.101"
        web.vm.provision "shell", path: "web.sh"
    end

    config.vm.define "db" do |db|
        db.vm.box="luki_strike/Ubuntu"
        db.vm.synced_folder ".", "/vagrant"
        db.vm.hostname = "db"
        db.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        db.vm.network "private_network", ip: "192.168.100.102"
        db.vm.provision "shell", path: "db.sh"
    end

end