# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false

    config.vm.box = "luki_strike/Exam"
    config.vm.box_version = "1.0"
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 1
    end
    config.vm.provision "shell", path: "hosts.sh"

    config.vm.define "docker" do |docker|
        docker.vm.hostname = "docker.do2.exam"
        docker.vm.network "private_network", ip: "192.168.100.101"
        docker.vm.provision "shell", path: "docker.sh"
        docker.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "manifests"
            puppet.manifest_file = "docker.pp"
        end
        docker.vm.provision "shell", path: "terraform.sh"
    end

    config.vm.define "web" do |web|
        web.vm.hostname = "web.do2.exam"
        web.vm.network "private_network", ip: "192.168.100.102"
        web.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.install_mode = :default
            ansible.playbook = "playbooks/playbook.yml"
        end
    end

    config.vm.define "db" do |db|
        db.vm.hostname = "db.do2.exam"
        db.vm.network "private_network", ip: "192.168.100.103"
        db.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.install_mode = :default
            ansible.playbook = "playbooks/playbook.yml"
        end
    end
end