# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false

    config.vm.define "web" do |web|
        web.vm.box="luki_strike/Ubuntu"
        web.vm.synced_folder ".", "/vagrant"
        web.vm.hostname = "web.do2.lab"
        web.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        web.vm.network "private_network", ip: "192.168.100.101"
        web.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.install_mode = :default
            ansible.playbook = "web/playbook.yml"
            ansible.galaxy_role_file = "web/requirements.yml"
            ansible.galaxy_roles_path = "/etc/ansible/roles"
            ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
        end
    end

    config.vm.define "db" do |db|
        db.vm.box="luki_strike/AlmaLinux"
        db.vm.synced_folder ".", "/vagrant"
        db.vm.hostname = "db.do2.lab"
        db.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        db.vm.network "private_network", ip: "192.168.100.102"
        db.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.install_mode = :default
            ansible.playbook = "db/playbook.yml"
            ansible.galaxy_role_file = "db/requirements.yml"
            ansible.galaxy_roles_path = "/etc/ansible/roles"
            ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
        end
    end

end