# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false

    config.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 1
    end

    config.vm.define "docker" do |docker|
        docker.vm.box = "luki_strike/Exam"
        docker.vm.box_version = "1.0"
        docker.vm.hostname = "docker.do2.exam"
        docker.vm.synced_folder ".", "/vagrant"
        docker.vm.network "private_network", ip: "192.168.100.101"
        docker.vm.provision "shell", path: "hosts.sh"
        docker.vm.provision "shell", path: "docker.sh"
        docker.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "manifests"
            puppet.manifest_file = "docker.pp"
            puppet.options = "--verbose --debug"
        end
        docker.vm.provision "shell", path: "terraform.sh"
    end

    config.vm.define "web" do |web|
        web.vm.box = "luki_strike/Exam"
        web.vm.box_version = "1.0"
        web.vm.hostname = "web.do2.exam"
        web.vm.synced_folder ".", "/vagrant"
        web.vm.network "private_network", ip: "192.168.100.102"
        web.vm.provision "shell", path: "hosts.sh"
        web.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.install_mode = :default
            ansible.playbook = "playbooks/playbook.yml"
            #ansible.galaxy_role_file = "playbooks/requirements.yml"
            #ansible.galaxy_roles_path = "/etc/ansible/roles"
            #ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
        end
    end

    config.vm.define "db" do |db|
        db.vm.box = "luki_strike/Exam"
        db.vm.box_version = "1.0"
        db.vm.hostname = "db.do2.exam"
        db.vm.synced_folder ".", "/vagrant"
        db.vm.network "private_network", ip: "192.168.100.103"
        db.vm.provision "shell", path: "hosts.sh"
        db.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.install_mode = :default
            ansible.playbook = "playbooks/playbook.yml"
            #ansible.galaxy_role_file = "playbooks/requirements.yml"
            #ansible.galaxy_roles_path = "/etc/ansible/roles"
            #ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
        end
    end
end