# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false

    config.vm.define "server" do |server|
        server.vm.box="luki_strike/Ubuntu"
        server.vm.synced_folder ".", "/vagrant"
        server.vm.hostname = "server.do2.lab"
        server.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        server.vm.network "private_network", ip: "192.168.100.101"
        server.vm.provision "shell", path: "hosts.sh"
        server.vm.provision "salt" do |sa|
            sa.minion_config = "salt/minion"
            sa.run_highstate = true
            sa.verbose = true
        end
    end

end