# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false

    config.vm.define "web" do |web|
        web.vm.box="luki_strike/Ubuntu"
        web.vm.hostname = "web.do2.lab"
        web.vm.synced_folder ".", "/vagrant"
        web.vm.provider :virtualbox do |v|
            v.memory = 1536
            v.cpus = 1
        end
        web.vm.network "private_network", ip: "192.168.100.201"
        web.vm.provision "chef_solo" do |chef|
            chef.product = "chef-workstation"
            chef.arguments = "--chef-license accept"
            chef.run_list = [
                "recipe[web::default]"
            ]
        end
    end

    config.vm.define "db" do |db|
        db.vm.box="luki_strike/AlmaLinux"
        db.vm.hostname = "db.do2.lab"
        db.vm.synced_folder ".", "/vagrant"
        db.vm.provider :virtualbox do |v|
            v.memory = 1536
            v.cpus = 1
        end
        db.vm.network "private_network", ip: "192.168.100.202"
        db.vm.provision "chef_solo" do |chef|
            chef.product = "chef-workstation"
            chef.arguments = "--chef-license accept"
            chef.run_list = [
                "recipe[db::default]"
            ]
        end
    end
end