# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
  
    config.vm.define "docker" do |docker|
        docker.vm.box="luki_strike/Ubuntu"
        docker.vm.synced_folder ".", "/vagrant"
        docker.vm.hostname = "docker"
        docker.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        docker.vm.network "private_network", ip: "192.168.100.101"
        docker.vm.provision "shell", path: "docker.sh"
    end

end