# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false

    config.vm.define "server" do |server|
        server.vm.box="luki_strike/Ubuntu"
        server.vm.synced_folder ".", "/vagrant"
        server.vm.hostname = "server.do2.lab"
        server.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        server.vm.network "private_network", ip: "192.168.100.101"
        server.vm.provision "shell", path: "master.sh"
    end

    config.vm.define "web" do |web|
        web.vm.box="luki_strike/Ubuntu"
        web.vm.synced_folder ".", "/vagrant"
        web.vm.hostname = "web.do2.lab"
        web.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        web.vm.network "private_network", ip: "192.168.100.102"
        web.vm.provision "shell", path: "minion.sh"
    end

    config.vm.define "db" do |db|
        db.vm.box="luki_strike/Ubuntu"
        db.vm.synced_folder ".", "/vagrant"
        db.vm.hostname = "db.do2.lab"
        db.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        db.vm.network "private_network", ip: "192.168.100.103"
        db.vm.provision "shell", path: "minion.sh"
    end

end