# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
  
    config.vm.define "docker" do |docker|
        docker.vm.box="luki_strike/Ubuntu"
        docker.vm.hostname = "docker.do2.lab"
        docker.vm.synced_folder ".", "/vagrant"
        docker.vm.provider :virtualbox do |v|
            v.memory = 2048
            v.cpus = 1
        end
        docker.vm.network "private_network", ip: "192.168.100.101"
        docker.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.install_mode = :default
            ansible.playbook = "playbook.yml"
            ansible.galaxy_role_file = "requirements.yml"
            ansible.galaxy_roles_path = "/etc/ansible/roles"
            ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
        end
    end
end