# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false

    config.vm.define "server" do |server|
        server.vm.box="luki_strike/Ubuntu"
        server.vm.hostname = "server.do2.lab"
        server.vm.synced_folder ".", "/vagrant"
        server.vm.provider :virtualbox do |v|
            v.memory = 1536
            v.cpus = 1
        end
        #server.vm.provision "shell", path: "server.sh"
        server.vm.network "private_network", ip: "192.168.100.201"
    end

    config.vm.define "client" do |client|
        client.vm.box="luki_strike/Ubuntu"
        client.vm.hostname = "client.do2.lab"
        client.vm.synced_folder ".", "/vagrant"
        client.vm.provider :virtualbox do |v|
            v.memory = 1536
            v.cpus = 1
        end
        client.vm.provision "shell", path: "client.sh"
        client.vm.network "private_network", ip: "192.168.100.202"
    end
end